stages:
- build

build:
  stage: build
  image: g76r/qt6-builder:20230708
  variables:
    DOCKER_BUILD_ENABLED: "false"
  script:
    - git fetch --tags
    - git submodule update --init
    - qmake
    - make
  tags:
    - qt
    - c++
