stages:
- build

build_main:
  stage: build
  script:
    - git fetch --tags
    - git submodule update --init
    - qmake
    - make
  tags:
    - qt
    - c++
  artifacts:
    paths:
      - linux/qrond-linux-amd64.tar.bz2
      - doc/user-manual.html
