stages:
- build

linux:build:
  stage: build
  script:
    - git fetch --tags
    - git submodule update --init
    - qmake
    - make
  tags:
    - qt
    - c++
  artifacts:
    name: qrond-linux-amd64-$CI_COMMIT_REF_NAME.tar.bz2
    paths:
      - linux/qrond-linux-amd64.tar.bz2
    when: on_success
    expire_in: 1 year

user-manual:
  stage: build
  needs:
    - linux:build
  artifacts:
    name: user-manual-$CI_COMMIT_REF_NAME.html
    paths:
      - doc/user-manual.html
    when: on_success
    expire_in: 1 year

