stages:
- build

linux:build:
  stage: build
  variables:
    DOCKER_BUILD_ENABLED: "false"
  script:
    - git fetch --tags
    - git submodule update --init
    - qmake
    - make
  tags:
    - qt
    - c++
