#!/bin/bash
set -C -e -o pipefail
shopt -s lastpipe
SECRET_ID="${1:?}"
aws secretsmanager get-secret-value --secret-id "$SECRET_ID" | jq -r '.SecretString|fromjson|. as $o|($o|keys) as $keys|$keys[] |[.,$o[.]]|"\""+.[0]+"\",\""+(.[1] |gsub("(?<sc>[,\"\\\\])";"\\"+.sc))+"\""'
